DROP DATABASE IF EXISTS RESTAURANTES;
CREATE DATABASE RESTAURANTES;
--TABLA USUARIO
CREATE TABLE USUARIO(
	ID_USUARIO SERIAL PRIMARY KEY,
	NOMBRE VARCHAR(15) NOT NULL,
	APELLIDOS VARCHAR(30) NOT NULL,
	USERNAME VARCHAR(20) NOT NULL UNIQUE,
	PASSWORD VARCHAR(20) NOT NULL,
	EMAIL VARCHAR(20) NOT NULL,
	ROL VARCHAR(10),
	FECHA_NACIMIENTO DATE  NOT NULL,
	SEXO VARCHAR(10) NOT NULL,
	TELEFONO VARCHAR(15),
	CONFIRMATION_KEY VARCHAR(15),
	RESET_KEY VARCHAR(15),
	ID_COLABORADOR INTEGER NOT NULL,
	FOREIGN KEY (ID_COLABORADOR) REFERENCES USUARIO (ID_USUARIO)
);
-- TABLA REGISTRO_OPERACIONES
CREATE TABLE REGISTRO_OPERACIONES(
	ID_TIME SERIAL PRIMARY KEY,
	FECHA DATE,
	TIPO VARCHAR(15) NOT NULL,
	ID_USUARIO INTEGER NOT NULL,
	FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);
--TABLA RESPALDO
CREATE TABLE RESPALDO(
	ID_RESPALDO SERIAL,
	ID_TIME INTEGER NOT NULL,
	ID_USUARIO INTEGER NOT NULL,
	NOMBRE VARCHAR(15) NOT NULL,
	APELLIDOS VARCHAR(30) NOT NULL,
	USERNAME VARCHAR(20) NOT NULL UNIQUE,
	PASSWORD VARCHAR(20) NOT NULL,
	EMAIL VARCHAR(20) NOT NULL,
	ROL VARCHAR(10),
	FECHA_NACIMIENTO DATE  NOT NULL,
	SEXO VARCHAR(10) NOT NULL,
	TELEFONO VARCHAR(15),
	CONFIRMATION_KEY VARCHAR(15),
	RESET_KEY VARCHAR(15),
	ID_COLABORADOR INTEGER NOT NULL,
	PRIMARY KEY (ID_RESPALDO, ID_TIME),
	FOREIGN KEY (ID_TIME) REFERENCES REGISTRO_OPERACIONES(ID_TIME)

);
--TABLA COCINERO
CREATE TABLE COCINERO(
	ID_COCINERO SERIAL PRIMARY KEY,
	NOMBRE VARCHAR(15) NOT NULL,
	APELLIDOS VARCHAR(20) NOT NULL,
	ESPECIALIDAD VARCHAR(15) NULL,
	NACIONALIDAD VARCHAR(15) NOT NULL,
	FOTO VARCHAR(20) NOT NULL
);
--TABLA HORARIO
CREATE TABLE HORARIO(
	ID_HORARIO SERIAL PRIMARY KEY,
	HORA_APERTURA VARCHAR(5) NOT NULL,
	HORA_CIERRE VARCHAR(5) NOT NULL,
	NOMBRE_DIA VARCHAR(10) NOT NULL
);
--TABLA ESTABLECIMIENTO_GASTRONOMICO
CREATE TABLE ESTABLECIMIENTO_GASTRONOMICO(
	ID_EG SERIAL PRIMARY KEY,
	RAZON_SOCIAL VARCHAR(20) NOT NULL,
	TELEFONO VARCHAR(20) NULL,
	DESCRIPCION VARCHAR(100) NOT NULL,
	TIPO VARCHAR(15) NOT NULL,
	ID_HORARIO INTEGER NOT NULL,
	ID_COCINERO INTEGER NOT NULL,
	FOREIGN KEY (ID_COCINERO) REFERENCES COCINERO (ID_COCINERO),
	FOREIGN KEY (ID_HORARIO) REFERENCES HORARIO (ID_HORARIO)
);
--TABLA SUCURSAL
CREATE TABLE SUCURSAL(
	ID_SUSCURSAL SERIAL PRIMARY KEY,
	LATITUD VARCHAR(20) NOT NULL,
	LONGITUD VARCHAR(20) NOT NULL,
	DIRECCION VARCHAR(50) NOT NULL,
	ID_EG INTEGER NOT NULL,
	FOREIGN KEY(ID_EG) REFERENCES ESTABLECIMIENTO_GASTRONOMICO (ID_EG)
);
--TABLA VISITA
CREATE TABLE VISITA(
	ID_EG INTEGER NOT NULL,
	ID_USUARIO INTEGER NOT NULL,
	PRIMARY KEY(ID_EG, ID_USUARIO),
	FOREIGN KEY (ID_EG) REFERENCES ESTABLECIMIENTO_GASTRONOMICO (ID_EG),
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);
--TABLA CALIFICA
CREATE TABLE CALIFICA(
	ID_EG INTEGER NOT NULL,
	ID_USUARIO INTEGER NOT NULL,
	CALIFICACION INTEGER NOT NULL,
	PRIMARY KEY(ID_EG,ID_USUARIO),
	FOREIGN KEY (ID_EG) REFERENCES ESTABLECIMIENTO_GASTRONOMICO (ID_EG),
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);
--TABLA TIENE
CREATE TABLE TIENE(
	ID_EG INTEGER NOT NULL,
	ID_USUARIO INTEGER NOT NULL,
	NIT INTEGER NOT NULL UNIQUE,
	ES_ADMINISTRADOR BOOLEAN DEFAULT FALSE,
	PRIMARY KEY(ID_EG,ID_USUARIO),
	FOREIGN KEY (ID_EG) REFERENCES ESTABLECIMIENTO_GASTRONOMICO (ID_EG),
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);
--TABLA PUBLICIDAD
CREATE TABLE PUBLICIDAD(
	ID_PUBLICIDAD SERIAL PRIMARY KEY,
	TITULO VARCHAR(25) NOT NULL,
	FECHA_INI DATE,
	FECHA_FIN DATE,
	DESCRIPCION VARCHAR(100),
	IMAGEN_PRO VARCHAR(20) NOT NULL,
	COSTO DECIMAL(4,2),
	ID_EG INTEGER NOT NULL,
	FOREIGN KEY (ID_EG) REFERENCES ESTABLECIMIENTO_GASTRONOMICO (ID_EG)
);
--TABLA MENU
CREATE TABLE MENU(
	ID_MENU SERIAL PRIMARY KEY,
	TIPO_MENU VARCHAR(25) NULL,
	DETALLE_MENU VARCHAR(100),
	ID_EG INTEGER NOT NULL,
	FOREIGN KEY (ID_EG) REFERENCES ESTABLECIMIENTO_GASTRONOMICO (ID_EG)
);
--TABLA BEBIDAS
CREATE TABLE BEBIDAS(
	ID_BEBIDA SERIAL PRIMARY KEY,
	TIPO VARCHAR(15) NOT NULL,
	PRECIO_B DECIMAL(4,2),
	NOMBRE VARCHAR(20) NOT NULL,
	FOTO_B VARCHAR(20) NOT NULL
);
--TABLA PLATO_ESPECIAL
CREATE TABLE PLATO_ESPECIAL(
	ID_PLATO SERIAL PRIMARY KEY,
	PRECIO_P DECIMAL(4,2) NOT NULL,
	DESCRIPCION VARCHAR(100) NULL,
	NOMBRE VARCHAR(25) NOT NULL,
	FOTO_P VARCHAR(20) NOT NULL
);
--TABLA ALMUERZO
CREATE TABLE ALMUERZO (
	ID_ALMUERZO SERIAL PRIMARY KEY,
	PRECIO_A DECIMAL(4,2) NOT NULL,
	FOTO_A VARCHAR(20),
	ID_MENU INTEGER NOT NULL,
	FOREIGN KEY (ID_MENU) REFERENCES MENU(ID_MENU)
);
--TABLA OFRECE_PLATO_ESPECIAL
CREATE TABLE OFRECE_PLATO_ESPECIAL(
	ID_MENU INTEGER NOT NULL,
	ID_PLATO INTEGER NOT NULL,
	PRIMARY KEY (ID_MENU, ID_PLATO),
	FOREIGN KEY (ID_MENU) REFERENCES MENU(ID_MENU),
	FOREIGN KEY (ID_PLATO) REFERENCES PLATO_ESPECIAL(ID_PLATO)
);
--TABLA OFRECE_BEBIDAS
CREATE TABLE OFRECE_BEBIDAS(
	ID_MENU INTEGER NOT NULL,
	ID_BEBIDA INTEGER NOT NULL,
	PRIMARY KEY (ID_MENU, ID_BEBIDA),
	FOREIGN KEY (ID_MENU) REFERENCES MENU(ID_MENU),
	FOREIGN KEY (ID_BEBIDA) REFERENCES BEBIDAS(ID_BEBIDA)
);
--TABLA SEGUNDO
CREATE TABLE SEGUNDO(
	ID_SEGUNDO SERIAL PRIMARY KEY,
	NOMBRE VARCHAR(20) NOT NULL,
	DESCRIPCION VARCHAR(100) NULL,
	FOTO VARCHAR(20) NOT NULL
);
--TABLA TIENE_SEGUNDO
CREATE TABLE TIENE_SEGUNDO(
	ID_ALMUERZO INTEGER NOT NULL,
	ID_SEGUNDO INTEGER NOT NULL ,
	PRIMARY KEY (ID_ALMUERZO, ID_SEGUNDO),
	FOREIGN KEY (ID_ALMUERZO) REFERENCES ALMUERZO(ID_ALMUERZO),
	FOREIGN KEY (ID_SEGUNDO) REFERENCES SEGUNDO(ID_SEGUNDO)
);
--TABLA ENTRADA
CREATE TABLE ENTRADA(
	ID_ENTRADA SERIAL PRIMARY KEY,
	NOMBRE_AE VARCHAR(25) NOT NULL,
	DESCRIPCION_AE VARCHAR(100) NULL,
	ID_ALMUERZO INTEGER NOT NULL,
	TIPO VARCHAR(15) NOT NULL,
	FOREIGN KEY (ID_ALMUERZO) REFERENCES ALMUERZO(ID_ALMUERZO)
);
--TABLA SOPA
CREATE TABLE SOPA(
	ID_SOPA SERIAL PRIMARY KEY,
	NOMBRE_AS VARCHAR(25) NOT NULL,
	DESCRIPCION_AS VARCHAR(100) NULL,
	ID_ALMUERZO INTEGER NOT NULL,
	FOREIGN KEY (ID_ALMUERZO) REFERENCES ALMUERZO(ID_ALMUERZO)
);
--TABLA POSTRE
CREATE TABLE POSTRE(
	ID_POSTRE SERIAL PRIMARY KEY,
	NOMBRE_AP VARCHAR(25) NOT NULL,
	DESCRIPCION_AP VARCHAR(100) NULL,
	ID_ALMUERZO INTEGER NOT NULL,
	FOREIGN KEY (ID_ALMUERZO) REFERENCES ALMUERZO(ID_ALMUERZO)
);
--TABLA CALIFICA_ALMUERZO
CREATE TABLE CALIFICA_ALMUERZO(
	ID_ALMUERZO INTEGER NOT NULL,
	ID_USUARIO INTEGER NOT NULL,
	PUNTUACION INTEGER NOT NULL,
	PRIMARY KEY(ID_ALMUERZO, ID_USUARIO),
	FOREIGN KEY (ID_ALMUERZO) REFERENCES ALMUERZO(ID_ALMUERZO),
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);
--TABLA CALIFICA_BEBIDA
CREATE TABLE CALIFICA_BEBIDA(
	ID_BEBIDA INTEGER NOT NULL,
	ID_USUARIO INTEGER NOT NULL,
	PUNTUACION INTEGER NOT NULL,
	PRIMARY KEY(ID_BEBIDA, ID_USUARIO),
	FOREIGN KEY (ID_BEBIDA) REFERENCES BEBIDAS(ID_BEBIDA),
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);
--TABLA CLAIFICA_ESPECIAL
CREATE TABLE CALIFICA_ESPECIAL(
	ID_PLATO INTEGER NOT NULL,
	ID_USUARIO INTEGER NOT NULL,
	PUNTUACION INTEGER NOT NULL,
	PRIMARY KEY(ID_PLATO, ID_USUARIO),
	FOREIGN KEY (ID_PLATO) REFERENCES PLATO_ESPECIAL(ID_PLATO),
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);
--TABLA SERVICIO_EXTRA
CREATE TABLE SERVICIO_EXTRA(
	ID_SERVICIO SERIAL PRIMARY KEY,
	NOMBRE VARCHAR(15) NOT NULL
);
--TABLA OFRECE_SERVICIO
CREATE TABLE OFRECE_SERVICIO(
	ID_EG INTEGER NOT NULL,
	ID_SERVICIO INTEGER NOT NULL,
	PRIMARY KEY (ID_EG,ID_SERVICIO),
	FOREIGN KEY (ID_EG) REFERENCES ESTABLECIMIENTO_GASTRONOMICO(ID_EG),
	FOREIGN KEY (ID_SERVICIO) REFERENCES SERVICIO_EXTRA(ID_SERVICIO) 
);
--TABLA ADMINISTRA
CREATE TABLE ADMINISTRA(
	ID_EG INTEGER NOT NULL,
	ID_USUARIO INTEGER NOT NULL,
	PRIMARY KEY(ID_EG,ID_USUARIO),
	FOREIGN KEY (ID_EG) REFERENCES ESTABLECIMIENTO_GASTRONOMICO (ID_EG),
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);